feat: [ANDROAPP-3464] Create extra matomo tracker for implementations
dhis2/dhis2-android-capture-app pull request #1773
Opened 2020-11-05 16:12 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-3464)

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2020-11-10 12:40 UTC, JaimeToca commented on app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
> +        fun generateSecondaryTracker(
can you rename these trackers? For example: dhis2InternalTracker, dhis2ExternalTracker ?

2020-11-10 13:08 UTC, mmmateos approved these changes

2020-11-11 09:28 UTC, JaimeToca requested changes
asdasdas

2020-11-11 09:29 UTC, JaimeToca approved these changes

2020-11-11 15:28 UTC, merged