fix: [ANDROAPP-3824] autogenerated fields remain non-editable when focusing on other fields.
dhis2/dhis2-android-capture-app pull request #2034
Opened 2021-04-06 12:56 UTC by ferdyrod

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ ANDROAPP-3824](https://jira.dhis2.org/browse/ANDROAPP-3824)

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-04-06 13:48 UTC, JaimeToca commented
@ferdyrod this generates another problem, it was added for a reason. Call me and lets review the git log.
Adding @andresmr

2021-04-06 14:33 UTC, andresmr approved these changes

2021-04-06 15:03 UTC, JaimeToca approved these changes

2021-04-07 06:50 UTC, Balcan requested changes
withValue method was used to set edition to false when the assign rule action was performed. It seems this has changed (maybe during the form reworks).
I've checked that the EditTextViewModel keeps its editable parameter, but any other model set the edition to false.
So to "fix" this, we should change all viewModel withValue implementation to not change the editable parameter.

2021-04-07 09:14 UTC, Balcan approved these changes

2021-04-07 09:31 UTC, merged