fix: [ANDROAPP-4529] fab visibility after scan
dhis2/dhis2-android-capture-app pull request #2486
Opened 2022-01-20 13:02 UTC by mmmateos

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://jira.dhis2.org/browse/

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-01-20 15:18 UTC, andresmr requested changes

2022-01-20 15:18 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
> +                        !backDropActive
I would extract this to a method splitting responsibilities.
`setFabVisibility(isButtonVisible())`

2022-01-21 08:43 UTC, Balcan approved these changes

2022-01-21 10:59 UTC, andresmr approved these changes

2022-01-21 12:23 UTC, merged