Feature/legends in analytics
dhis2/dhis2-android-capture-app pull request #2538
Opened 2022-02-28 14:15 UTC by ifoche

## Description
This PR contains the implementation, using the current code of the app, for the legends in TEI analytics and visualizations analytics as they are implemented in the following SDK PR:
https://github.com/dhis2/dhis2-android-sdk/pull/1733

Please refer to that PR in order to test this PR, in particular the multiple heads-up that are described there regarding how to test it and the limitations that we have found.

## Solution description
The implementation of this PR includes the following main solutions:
- Add legendValue to GraphPoint
- Set LegendValue to GraphPoint
- Render color by legend in tables and single values

## Where did you test this issue?
- [x] Smartphone Emulator
- [ ] Tablet Emulator
- [x] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [x] 9.X - 10.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-02-28 15:21 UTC, Balcan approved these changes

2022-03-04 09:53 UTC, andresmr requested changes
Hi, the code looks great, just some comments to meet requirements related to code style and unit test.
- The code looks good, but you don't meet checkStyle, please run:
`./gradlew dhis_android_analytics:ktlintCheck` to see the issues and solve them.

- `ChartCoordinatesProviderImplTest` is failing, please fix it.

2022-03-07 09:23 UTC, ifoche commented on dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
> +        context: Context,
@andresmr thanks for your very pertinent comment. We will submit the fix to this shortly.

2022-03-07 15:14 UTC, andresmr requested changes
Hi, my previous comments where properly solved, thanks!. The only thing missing is ChartCoordinatesProviderImplTest are failing beacuse of the change of `ChartCoordinatesProviderImpl`, please take a look. thanks!

2022-03-07 15:14 UTC, andresmr commented on dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/providers/ChartCoordinatesProviderImplTest.kt
>      fun `Should get coordinates for data elements`() {
These four tests are failing, producing a null pointer exception in `ChartCoordinatesProviderImpl line 47`. Please check it and run the tests.

2022-03-10 07:06 UTC, andresmr commented
Hi, please update SDK branch to develop and solve the small conflict. This will be all :). Thanks!

2022-03-10 14:10 UTC, merged