fix: [ANDROAPP-4507, ANDROAPP-4652] Improve focus handler in forms
dhis2/dhis2-android-capture-app pull request #2579
Opened 2022-03-24 10:01 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4507)
[ jira issue ](https://jira.dhis2.org/browse/ANDROAPP-4652)

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-03-24 10:56 UTC, andresmr requested changes

2022-03-24 10:56 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
>      }
Could you delete this commented code?

2022-03-29 12:02 UTC, mmmateos approved these changes

2022-03-30 06:00 UTC, andresmr approved these changes

2022-03-31 13:27 UTC, merged