feat: [ANDROAPP-5180] use Material3 theme
dhis2/dhis2-android-capture-app pull request #3034
Opened 2023-02-07 07:22 UTC by mmmateos

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-02-07 11:54 UTC, Balcan approved these changes

2023-02-09 10:40 UTC, andresmr requested changes

2023-02-09 10:40 UTC, andresmr commented on ui-components/build.gradle
> +    api "com.google.accompanist:accompanist-themeadapter-material3:0.28.0"
please, can you check if there is already one dependencies in `dependencies.gradle`, if not create it. thanks!

2023-02-14 08:22 UTC, andresmr approved these changes

2023-02-15 09:08 UTC, merged