fix: [ANDROAPP-5132] Go back to relationship fragment when TEI is selected/created
dhis2/dhis2-android-capture-app pull request #3061
Opened 2023-02-22 14:23 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-02-23 08:38 UTC, mmmateos approved these changes

2023-02-28 07:54 UTC, andresmr requested changes
please, update your branch to solve conflicts

2023-02-28 07:54 UTC, andresmr commented on compose-table/build.gradle
> +    androidTestImplementation("androidx.test.uiautomator:uiautomator:2.2.0")
are going to move all the version to the new dependencies?

2023-03-02 10:24 UTC, andresmr approved these changes

2023-03-02 15:14 UTC, merged