fix: [ANDROAPP-5413] Review all ignored tests in TeiDashboardTest file
dhis2/dhis2-android-capture-app pull request #3250
Opened 2023-07-28 13:56 UTC by DavidAparicioAlbaAsenjo

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-07-30 08:03 UTC, xavimolloy requested changes
PR was on Master, remove commented code and rebase branch

2023-07-30 08:03 UTC, xavimolloy commented on app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
> +    //@Ignore("SDK related, also indeterminate")
Must remove all commented code

2023-07-30 08:03 UTC, xavimolloy commented on app/src/main/java/org/dhis2/App.java
> +        if(BuildConfig.DEBUG){
There are changes in the PR that are not related to the issue, remember rebase with develop

2023-08-02 06:16 UTC, andresmr requested changes

2023-08-02 06:16 UTC, andresmr commented on app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
> +            // checkEventCreatedToastIsShown()
please, remove commented code

2023-08-02 06:16 UTC, andresmr commented on app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
> +          //  checkEventCreatedToastIsShown()
Please, remove commented code

2023-08-03 09:40 UTC, andresmr approved these changes

2023-08-03 09:43 UTC, xavimolloy approved these changes

2023-08-03 09:45 UTC, merged