ANDROAPP-5743-Bug-Calculated-variables-save-integer-values-with-.0
dhis2/dhis2-android-capture-app pull request #3418
Opened 2023-11-24 08:33 UTC by DavidAparicioAlbaAsenjo

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-11-24 08:51 UTC, xavimolloy approved these changes

2023-11-24 10:03 UTC, andresmr requested changes
branch should come from `develop` and PR to `develop`

2023-11-24 10:28 UTC, andresmr requested changes
There is a `RuleExtensionsTest`, could you create a test to cover this behavours?:
One for a Integer value
One for a Number
One for other values?
Thanks!

2023-11-30 09:24 UTC, mmmateos approved these changes

2023-12-01 07:51 UTC, merged