feat: [ANDROAPP-5726] RTS workflow needs to allow for translating the 3 transaction types
dhis2/dhis2-android-capture-app pull request #3444
Opened 2023-12-19 10:48 UTC by xavimolloy

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-12-20 13:39 UTC, andresmr requested changes

2023-12-20 13:39 UTC, andresmr commented on stock-usecase/src/main/java/org/dhis2/android/rtsm/data/models/TransactionItem.kt
> +    val transactionTypelabel: String,
I think `label` should be fine as the class is already called TranscationItem, maybe `transactionType` will be enough with `type` as well...

2023-12-22 11:19 UTC, andresmr approved these changes

2023-12-22 13:50 UTC, ferdyrod approved these changes

2023-12-26 13:01 UTC, merged