[ANDROAPP-5800] Search parameters
dhis2/dhis2-android-capture-app pull request #3497
Opened 2024-02-13 09:36 UTC by andresmr

2024-02-13 12:52 UTC, xavimolloy requested changes

2024-02-13 12:52 UTC, xavimolloy commented on app/src/main/java/org/dhis2/usescases/searchTrackEntity/searchparameters/SearchParametersScreen.kt
> +                    text = "Clear search",
please remove hardcoded text

2024-02-13 12:52 UTC, xavimolloy commented on app/src/main/java/org/dhis2/usescases/searchTrackEntity/searchparameters/SearchParametersScreen.kt
> +                text = "Search",
please remove hardcoded text

2024-02-13 16:02 UTC, ferdyrod approved these changes

2024-02-15 13:25 UTC, xavimolloy approved these changes

2024-02-23 10:20 UTC, merged