Androapp 5790 cards design for program stages
dhis2/dhis2-android-capture-app pull request #3502
Opened 2024-02-19 12:37 UTC by siddh1004

## Description
This Pr includes the logic update to show/hide grouped and timeline events

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-5790)

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-02-20 08:05 UTC, Balcan approved these changes

2024-02-20 14:03 UTC, xavimolloy approved these changes

2024-02-26 09:02 UTC, andresmr requested changes
please update branch and solve CI errors

2024-02-29 07:11 UTC, xavimolloy approved these changes

2024-02-29 07:12 UTC, xavimolloy reviewed
it appears some UI tests have failed, can you run them locally to verify that they are not flaky tests?

2024-02-29 07:13 UTC, xavimolloy reviewed
Ci not successful

2024-03-01 13:31 UTC, andresmr approved these changes

2024-03-07 13:25 UTC, merged