[ANDROAPP-5941] Use multiplatform rule engine
dhis2/dhis2-android-capture-app pull request #3505
Opened 2024-02-26 12:51 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-02-28 07:43 UTC, xavimolloy approved these changes

2024-02-28 09:55 UTC, andresmr commented on app/src/main/java/org/dhis2/data/forms/EventRepository.java
As this class also extends from FormRepository and as I see the three of them (interface and both implementations) are focused in the rule engine, do you think is there any way to merge it in only one class renamed to something more understandable of it's missing, something related to rule engine?

2024-02-28 09:55 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
Great work here!, this class gets to tiny, maybe we can remove it in the future! 💪🏽

2024-02-29 10:23 UTC, andresmr requested changes

2024-02-29 10:23 UTC, andresmr commented on gradle/libs.versions.toml
> +kotlin1921 = "1.9.21"
we already have these dependencies, they are:
```
gradle = "8.2.2"
kotlin = '1.9.21'
```

2024-03-04 09:46 UTC, andresmr approved these changes

2024-03-07 15:16 UTC, merged