ANDROAPP-5013-Align-app-buttons-to-new-material-design
dhis2/dhis2-android-capture-app pull request #3513
Opened 2024-03-05 14:22 UTC by DavidAparicioAlbaAsenjo

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-03-06 07:14 UTC, xavimolloy requested changes
please review CI

2024-03-06 07:14 UTC, xavimolloy commented on app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventDetails/ui/ReopenButton.kt
> +            text = "Re-open form",
please remove this hard-coded text

2024-03-07 10:32 UTC, andresmr approved these changes

2024-03-08 10:38 UTC, andresmr approved these changes

2024-03-14 09:33 UTC, andresmr approved these changes

2024-03-19 09:07 UTC, andresmr approved these changes

2024-03-19 11:17 UTC, andresmr approved these changes

2024-04-16 09:06 UTC, merged