fix: [ANDROAPP-6062] clear search fields when required attributes to search
dhis2/dhis2-android-capture-app pull request #3581
Opened 2024-04-11 09:54 UTC by mmmateos

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-04-11 11:38 UTC, xavimolloy approved these changes

2024-04-19 08:50 UTC, andresmr requested changes

2024-04-19 08:50 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEIViewModel.kt
> +        searching = false
could you cover this change with a test, maybe performing the clear and then asserting the uiState?

2024-04-25 08:54 UTC, andresmr approved these changes

2024-04-29 10:36 UTC, merged