fix: [ANDROAPP-6103] month value in scheduling dialog
dhis2/dhis2-android-capture-app pull request #3590
Opened 2024-04-16 10:28 UTC by mmmateos

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-04-16 13:22 UTC, andresmr requested changes

2024-04-16 13:22 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt
> +        calendar[year, month - 1, day, 0, 0] = 0
why do we need to remove 1 in the month?

2024-04-16 13:22 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/teiDashboard/dialogs/scheduling/SchedulingViewModel.kt
could you add a test for this method with some different examples?

2024-04-17 09:57 UTC, ferdyrod approved these changes

2024-04-18 11:08 UTC, andresmr approved these changes

2024-04-18 12:42 UTC, merged