fix: [ANDROAPP-6277] Working lists not filtering search results
dhis2/dhis2-android-capture-app pull request #3704
Opened 2024-06-27 09:51 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-06-28 08:47 UTC, ferdyrod approved these changes

2024-07-01 06:32 UTC, xavimolloy approved these changes

2024-07-12 06:19 UTC, andresmr requested changes

2024-07-12 06:19 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt
> +                !FilterManager.getInstance().sameFilters(searchRepositoryJava.savedFilters)
why don't we inject the `FilterManager` by constructor in order to mock it?

2024-07-12 06:19 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImplKt.kt
> +        return if (isOnline && FilterManager.getInstance().stateFilters.isEmpty()) {
Can you do a  couple of tests to assert that filter with working list and not filter when no working list selected?

2024-07-12 06:24 UTC, closed without merging