fix: [ANDROAPP-6272] update displayOrgUnitName value using mutable live data
dhis2/dhis2-android-capture-app pull request #3720
Opened 2024-07-09 08:29 UTC by xavimolloy

…ve data

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-07-09 09:36 UTC, ferdyrod approved these changes

2024-07-09 09:39 UTC, andresmr requested changes

2024-07-09 09:39 UTC, andresmr commented on app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListViewModel.kt
> +                                    displayOrgUnit = displayOrgUnitName.value ?: true,
What do you think about create a test in `EventListViewModel` to assert the `eventModel` object and check `displayOrgUnit` property has expected value?

2024-07-15 13:53 UTC, andresmr approved these changes

2024-07-16 08:36 UTC, merged