[ANDROAPP-6114] Implement search when capturing coordinates
dhis2/dhis2-android-capture-app pull request #3799
Opened 2024-09-20 11:12 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-09-27 12:03 UTC, andresmr requested changes

2024-09-27 12:03 UTC, andresmr commented on dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorViewModel.kt
> +    suspend fun performLocationSearch(query: String = _searchLocationQuery.value) {
Can you create a test for this method?

2024-10-01 07:16 UTC, mmmateos commented on dhis2_android_maps/src/main/java/org/dhis2/maps/views/MapSelectorScreen.kt
> +                        searchedTitle = "Selected location",
Could you add the texts in this class to string resources so that it can be translated?

2024-10-01 07:16 UTC, mmmateos commented on dhis2_android_maps/src/main/java/org/dhis2/maps/extensions/FeatureExtensions.kt
> +    addBooleanProperty("selected", selected)
What do you thing about use constants instead of plain text for this properties?

2024-10-01 13:53 UTC, andresmr approved these changes

2024-10-01 14:25 UTC, mmmateos approved these changes

2024-10-10 06:30 UTC, andresmr approved these changes

2024-10-10 07:33 UTC, mmmateos approved these changes

2024-10-11 09:57 UTC, merged