fix: [ANDROAPP-6508] Files and images downloaded on devices lower than Android 10
dhis2/dhis2-android-capture-app pull request #3870
Opened 2024-11-07 13:37 UTC by ferdyrod

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-11-07 14:58 UTC, andresmr requested changes

2024-11-07 14:58 UTC, andresmr commented on form/src/main/java/org/dhis2/form/ui/FormView.kt
> +    private var fileName: String? = null
is there any way to store it in the viewModel instead of the view?

2024-11-08 08:39 UTC, Balcan approved these changes

2024-11-08 14:49 UTC, andresmr approved these changes

2024-11-11 10:47 UTC, merged