feat: [ANDROAPP-6689] Create DataSetInstanceScreen
dhis2/dhis2-android-capture-app pull request #3947
Opened 2024-12-20 14:14 UTC by Balcan

## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://dhis2.atlassian.net/browse/ANDROAPP-

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] 11.X - 13.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2025-01-08 12:08 UTC, andresmr requested changes

2025-01-08 12:08 UTC, andresmr commented on gradle/libs.versions.toml
> +dhis2-mobile-designsystem = { group = "org.hisp.dhis.mobile", name = "designsystem", version.ref = "designSystem" }
do you remember that we changed this time ago because it wasn't getting right the snapshot version?

2025-01-08 12:08 UTC, andresmr commented on stock-usecase/build.gradle.kts
> +    implementation(project(":aggregates"))
why stock use case should know aggregates? shouldn't use the table directly?

2025-01-08 12:17 UTC, xavimolloy approved these changes
amazing job!

2025-01-08 14:27 UTC, Balcan commented on gradle/libs.versions.toml
> +dhis2-mobile-designsystem = { group = "org.hisp.dhis.mobile", name = "designsystem", version.ref = "designSystem" }
yes. I found what the problem was and fix it. It was related on how the repositories are defined

2025-01-08 14:28 UTC, Balcan commented on stock-usecase/build.gradle.kts
> +    implementation(project(":aggregates"))
Yep. Not needed as the table will be consumed form the mobile ui

2025-01-08 14:29 UTC, Balcan commented on aggregates/src/commonMain/kotlin/org/dhis2/mobile/aggregates/ui/DataSetTableScreen.kt
> +            .height(48.dp)
I think it would make more sense to add this AdaptativeTabRow to the mobile ui.

2025-01-08 14:31 UTC, Balcan commented on aggregates/build.gradle.kts
> +    /*listOf(
Not now. I'll remove it. But i think we should be adding the iOS target in the new multiplatform modules if possible.

2025-01-15 13:18 UTC, andresmr approved these changes

2025-01-15 13:18 UTC, andresmr commented on aggregates/build.gradle.kts
> +repositories{
do you need this?. It isn't added in all repositories {...} in the root gradle?

2025-01-15 13:20 UTC, Balcan commented on aggregates/build.gradle.kts
> +repositories{
I think it makes sense to include the repositories in the module so that it can be use straightfoward without adding anything else to the main build.gradle

2025-01-20 13:48 UTC, merged